jboolean/1940s.nyc

- backend/serverless.yml
- backend/src/api/TipsResource.ts
- backend/src/createConnection.ts
- frontend/src/app.less
- frontend/src/screens/App/index.tsx
- frontend/src/screens/App/screens/MapPane/components/TipJar/TipJar.less
- frontend/src/screens/App/screens/MapPane/components/TipJar/index.tsx
- frontend/src/screens/App/screens/MapPane/components/TipJar/redirectToCheckout.ts
- frontend/src/shared/components/Modal/modal.less
Also, don't show welcome on cancel
And remove query string on load so it's not bookmarked or shared
> Add suggested tips

- frontend/src/screens/App/screens/MapPane/index.tsx
- frontend/src/shared/utils/OptimizeExperiments.tsx
Auto-open tip jar after two minutes on the map.
> Experiment to auto-open tip jar

- backend/convertImage.js
- backend/convertImage.ts
- backend/src/image-processing/LaserdiscUtils.ts
Remove the superimposed banner and all the black around portrait photos
> When processing images crop Laserdisc stills

- backend/src/api/PhotosResource.ts
Used to get alternates at the same point that would otherwise be covered up.
Will also be useful when there are multiple collections (1980s)
> API to get list of photos with matching lng, lat

- frontend/src/screens/App/screens/MapPane/components/TipJar/index.tsx
After several requests by email.
> Add link to PayPal

- backend/package-lock.json
- backend/package.json
- backend/src/api/GeodataResource.ts
- backend/src/app.ts
- backend/src/business/GeodataService.ts
- backend/src/entities/EffectiveGeocode.ts
Initial version of endpoint to create geojson.
It is very slow, and needs some work. Cause unknown—seems to not actually be streaming to response.
Requested by author of openhistorymap.org for data importation into that site.
> Endpoint to create geojson

- frontend/package-lock.json
- frontend/package.json
Reverts jboolean/1940s.nyc#445
> Revert "Bump css-loader from 5.2.7 to 6.5.1 in /frontend"

- frontend/src/screens/App/screens/AnnouncementBanner/AnnouncementBanner.less
- frontend/src/screens/App/screens/AnnouncementBanner/index.tsx
- frontend/src/screens/App/screens/ViewerPane/ViewerPane.less
- frontend/src/screens/App/screens/ViewerPane/components/Alternates/Alternates.less
- frontend/src/screens/App/screens/ViewerPane/components/Alternates/index.tsx
- frontend/src/screens/App/screens/ViewerPane/index.tsx
- frontend/src/shared/utils/photosApi.ts
Fetch alternate photos and show them in a filmstrip
> Browse alternate photos at the same lng,lat

- .github/workflows/backend-deploy.yml
- .github/workflows/backend-pr.yml
- backend/package-lock.json
- backend/package.json
- backend/secrets.dev.yml.encrypted
- backend/secrets.production.yml.encrypted
- backend/serverless.yml
Remove hacky plugin that won't work in serverless v3
Secrets are now loaded from AWS, even in dev.
> Move to SSM for secrets management

- backend/.eslintrc
- backend/package-lock.json
- backend/package.json
- backend/src/api/GeodataResource.ts
- backend/src/api/PhotosResource.ts
- backend/src/business/GeodataService.ts
- frontend/.eslintrc
- frontend/package-lock.json
- frontend/package.json
- frontend/src/react-unstable-attributes.d.ts
- frontend/src/screens/App/index.tsx
- frontend/src/screens/App/screens/AnnouncementBanner/index.tsx
- frontend/src/screens/App/screens/ImageGrid/index.tsx
- frontend/src/screens/App/screens/MapPane/components/MainMap/index.tsx
- frontend/src/screens/App/screens/MapPane/components/MainMap/overlays.ts
- frontend/src/screens/App/screens/MapPane/components/Search/index.tsx
- frontend/src/screens/App/screens/MapPane/components/TipJar/ThankYou.tsx
- frontend/src/screens/App/screens/MapPane/components/TipJar/index.tsx
- frontend/src/screens/App/screens/MapPane/components/TipJar/useAmountPresets.ts
- frontend/src/screens/App/screens/MapPane/index.tsx
- frontend/src/screens/App/screens/Shutdown/index.tsx
- frontend/src/screens/App/screens/ViewerPane/components/Alternates/index.tsx
- frontend/src/screens/App/screens/ViewerPane/components/ImageSwitcher.tsx
- frontend/src/screens/App/screens/Welcome/Carousel.tsx
- frontend/src/screens/App/screens/Welcome/index.tsx
- frontend/src/shared/utils/OptimizeExperiments.tsx
- frontend/src/shared/utils/Require.ts
- frontend/src/shared/utils/photosApi.ts
- frontend/src/typings.d.ts
- frontend/tsconfig.json
Eslint config was largely based on an ancient squarespace config.
Created my own config based on recommended configs and some tweaks.
fixed or ignored resulting issues
> Extract eslint config to another repo and make stricter

- backend/src/api/PhotosResource.ts
> Update prints order URL

- backend/package-lock.json
- backend/package.json
- backend/src/api/PhotosResource.ts
- backend/src/entities/GeocodeResult.ts
Fix breaking changes
Ignore deprecations
> Upgrade to typeorm 0.3

- backend/package-lock.json
- backend/package.json
- backend/src/api/PhotosResource.ts
- backend/src/entities/GeocodeResult.ts
This reverts commit a03a964fe921a1beff53ad9724c73fd4d29172ec, reversing
changes made to 95d4dab11e625ac5cff893037fe679e44e3527f7.
Something started causing extra database CPU usage around 10/25.
This is the only possible lead so far, though without any evidence.
> Revert "Merge pull request #667 from jboolean/typeorm-0.3"

- backend/package-lock.json
- backend/package.json
- backend/src/api/PhotosResource.ts
- backend/src/entities/GeocodeResult.ts
Reverts jboolean/1940s.nyc#698
Let's try again
> Revert "Revert "Merge pull request #667 from jboolean/typeorm-0.3""

- frontend/src/screens/App/screens/ViewerPane/ViewerPane.less
- frontend/src/screens/App/screens/ViewerPane/components/Alternates/Alternates.less
- frontend/src/screens/App/screens/ViewerPane/components/Overlay/Overlay.less
- frontend/src/screens/App/screens/ViewerPane/components/Overlay/index.tsx
- frontend/src/screens/App/screens/ViewerPane/index.tsx
- frontend/src/shared/styles/fadeTransition.less
Use JS instead of CSS.
Properly handle touch devices instead of relying on synthetic mouse events.
Allow touching to hide controls. Previously they could not be hidden once shown. 
Peek in for a bit so people know the controls are there.
> Refactor image overlay

- frontend/src/screens/App/screens/MapPane/components/Search/utils/geosearch.ts
v1 is gone
https://github.com/NYCPlanning/labs-geosearch-docker/blob/master/MIGRATING.md
> Upgrade to geosearch v2

- frontend/src/app.less
- frontend/src/screens/App/screens/SubmitStoryWizard/components/StorytellerInfo.tsx
Show legal test instead
see https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed
> Hide the recaptcha badge

- frontend/src/screens/App/screens/ViewerPane/components/ImageButtons.tsx
Maybe it will be more inviting
> Try "Know this Place?"

- backend/package-lock.json
- backend/package.json
- backend/serverless.yml
This reverts commit e78595b15ab351cd424df6fcb5578b1286b9b86d.
> Revert "Change default stage to dev, fix conditional deploys of prod-only function"

- frontend/src/screens/App/screens/SubmitStoryWizard/components/IntroGraph.tsx
- frontend/src/screens/App/screens/SubmitStoryWizard/components/TextContent/index.tsx
try to encourage more than just the place name or address
> minor copy changes to story intro

- frontend/src/screens/App/screens/Welcome/index.tsx
> Emphasize "every dot is a photo"

- frontend/src/screens/App/screens/Welcome/index.tsx
- frontend/src/screens/App/screens/Welcome/welcome.less
Wow I should have done this ages ago. I watch people struggle to figure out what to do on this page, but never did this simple fix.
> Move welcome modal CTA button above tho fold

- backend/src/api/TipsResource.ts
- frontend/src/screens/App/screens/TipJar/useAmountPresets.ts
Let's try some different amounts again. 
Last price test was in Nov 2020 and was mostly a tie.
> Second price test

- frontend/src/screens/App/index.tsx
> Url to open the tip jar

- frontend/src/screens/App/screens/Welcome/index.tsx
> update 404 link to nyc gov t&c page

- backend/src/api/PhotosResource.ts
- frontend/src/screens/App/screens/ViewerPane/components/ImageButtons.tsx
Pass UTM tags to DORIS in hopes that they notice I'm sending them referrals.
Also add my own tracking event so I can see how often this is used.
> Order prints tracking

- frontend/src/screens/App/screens/CreditPurchaseModal/index.tsx
> Some refinements to the color modal copy

- frontend/src/screens/App/screens/MapPane/index.tsx
- frontend/src/screens/App/screens/ViewerPane/components/ImageButtons.tsx
Based on a lot of email I've received, people think DORIS and 80s.nyc are my sites. 
I've received a lot of emails assuming I am responsible for prints orders.
Now it's even more important because there may be an expectation that 40s prints include AI color.
There does seem to be a small bug that if you wait for more than 5 seconds the link does not continue. Not sure what's up with this.
> External link warnings

- frontend/src/screens/App/screens/AnnouncementBanner/AnnouncementRegistry.tsx
- frontend/src/screens/App/screens/ViewerPane/components/ColorizeButton.tsx
- frontend/src/screens/App/shared/types/FeatureFlag.ts
Removes the feature flag and experiment and launches the Colorization feature to 100%
> Release colorization 100%

- backend/src/business/ledger/LedgerService.ts
- frontend/src/screens/App/screens/CreditPurchaseModal/index.tsx
Cut free usage to 1, reduce secret credits given for tips
> Cut color costs

- backend/src/api/ColorizationController.ts
Use the default price
Now we can change the price in Stripe
> Hardcode product not price

- backend/src/api/PostmarkWebhooksResource.ts
- backend/src/api/stories/StoryApiModel.ts
- backend/src/api/stories/storyToApi.ts
- backend/src/app.ts
- backend/src/entities/Story.ts
- frontend/src/screens/App/screens/Admin/screens/ReviewStories/index.tsx
- frontend/src/screens/App/shared/types/Story.ts
Listen to postmark webhooks, record bounces, display warning in review queue
> Flag email bounces in review queue

- frontend/src/screens/App/screens/Admin/screens/ReviewStories/index.tsx
> Only show captcha score if its low

- backend/src/api/stories/StoryApiModel.ts
- backend/src/api/stories/storyToApi.ts
- backend/src/business/stories/StoryUserEmailService.ts
- backend/src/repositories/StoryRepository.ts
We need to actually use the effective address, which includes corrections!
> Use effective address

- backend/serverless.yml
I can't respond to it at that hour
> Move daily job to not the middle of the night

- backend/convertImage.ts
- backend/serverless.yml
- backend/src/image-processing/ImageAdjustUtils.ts
Make images less washed out.
We are re-importing images now that better ones are on Preservica.
> Apply normalization when converting images

- backend/convertImage.ts
The new images are too big, we need another size for the image viewer.
> Add 720w and make progressive

- frontend/src/screens/App/screens/Welcome/welcome.less
> Use cap height numerals in title

- backend/convertImage.ts
- backend/package-lock.json
- backend/package.json
- backend/src/business/color/ColorService.ts
Remove from production dependencies, as it should be included in lambda.
> Upgrade AWS SDK to v3

- frontend/src/screens/App/screens/Corrections/components/LocationPickerModal.tsx
- frontend/src/screens/App/screens/Corrections/components/SelectAlternates.less
- frontend/src/screens/App/screens/Corrections/components/SelectAlternates.tsx
- frontend/src/screens/App/screens/Corrections/index.tsx
- frontend/src/screens/App/screens/Corrections/stores/CorrectionsStore.ts
- frontend/src/shared/styles/ui.less
- Show lot labels from new lot labels layer
- Select all / deselect all buttons
- Attestation checkbox
> Corrections improvements

- backend/src/business/stories/StoriesService.ts
Auto-reject banned users' stories
> Add auto-review logic to reject banned users' stories
